### ISSUE TITLE
[Revamp] Deprecate Karel Pascal

### ISSUE THREAD

**Issue by kishtarn555** [kishtarn555/rekarel-core#15]
Deprecate Karel Pascal

If so: https://github.com/kishtarn555/rekarel-core/issues/14 might be useful

# Deprecation options

## Soft:
   Give a compilation warning if you are using pascal "As of october 2024, Karel pascal is considered obsolete and has less features than Java"
  
## Hard:
   Compilation error "As of october 2024, Karel Pascal is no longer supported, ReKarel has support to change Pascal codes into Java"

**Comment by ccepeda** [comment]
There is really no gain in deprecating one language unless keeping it is troublesome. The changes proposed in Karel are small and the core should be language agnostic.

**Comment by kishtarn555** [comment]
@ccepeda Actually, there was a (lazy) reason for deprecating pascal, before, each parser also had it's own IR to opcode generator. So I was going to have to do every new addition twice. But I refactored it to do the IR processing outside the parsers

The image below shows the change, (the IR steps in blue are revamp stuff)




![Image](https://github.com/user-attachments/assets/830f5037-11eb-4f4e-9c38-0ac9f1fb4513)



The IR is almost opcode, but variables and calls are in a different format, also, IR has extra info in the opcodes for error generation
