### ISSUE TITLE
[Revamp] Add boolean functions

### ISSUE THREAD

**Issue by kishtarn555** [kishtarn555/rekarel-core#16]
```cpp

bool isPrime() {
    // Do stuff here
    if (facingNorth)
        return true;
    else
        return facingNorth;
}


void someOther() {
  if (isPrime()) {
    return;
  }
  // Do stuff
}


```

**Comment by ccepeda** [comment]
Although this can be substituted with int functions and comparison operators, the concept of a boolean value is important inside program structures like if and while. Since Karel is supposed to be a highly conceptual language, I consider the differentiation between int and bool is valuable.
