### ISSUE TITLE
Handling of infinite values

### ISSUE THREAD

**Issue by gabriel-ir** [kishtarn555/rekarel-core#183]
This is my proposal of the way infinite should be handled:

1. There must be a function called **isInfinite(n)**  which would return _true_ or _false_, according to its parameter's value.

2. It shoudn't be allowed to use **INF** in any operation, so things like: _succ(n, INF)_, _pickbeeper(INF)_, etc. should raise a RTE. Even things like _if(n < INF)_ woudn't be necessary, and then shouldn't be allowed.

The reason: **INF** is not a concrete number, it's just a concept. In addition, Karel shoudn't be able to pick up an infinite quantity of beepers, because, for the nature of the "infinite" concept, Karel would never finish picking up them. The same applies for _putbeeper(INF)_.

3. _int_max + 1_ should result in a **int_min** value, such as C++ does (and the same applies to **int_min - 1**), or in any case lead to a RTE.

I hope you like my proposal.

**Comment by kishtarn555** [comment]
Fixed on v2.3.0

1. Implemented isinfinite(n) function
2. That may be discussed for Karel v3, currently, pickbeeper does not take and argument, there's no INF constant
3. int_max +1 and int_min -1 lead to RTE
