### ISSUE TITLE
[Revamp] Add comparison operators

### ISSUE THREAD

**Issue by kishtarn555** [kishtarn555/rekarel-core#20]
* Equal to
* Not equal to
* Less than
* More than
* Less than or equal to
* More than or equal to

`void fibonacci(n) {
  if (n == 0) return();
  if (n <= 2) {
    putbeeper();
    return():
  }
  fibonacci(pred(n, 1));
  fibonacci(pred(n, 2));

}
`

**Comment by ccepeda** [comment]
Comparison operators together with the backpack and floor globals allow for solving some traditional Karel tasks with much shorter code. But they don't really add new functionality or drastically change the "Karel-spirit".  Is a small change that can leverage Karel into new interesting areas.

The valid operators should be ==, <, <=.  (!=, >, >= can be achieved with the "not" operator)
